import type { Metadata } from 'next';
import { Fira_Code, Poppins } from 'next/font/google';

import './globals.css';

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poppins',
});

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--fira-code',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${firaCode.variable} $ antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
